name = "Gemel"
version = "0.1.0"
defaultTargets = ["Gemel"]
testDriver = "GemelTest"
 
[[lean_lib]]
name = "Gemel"

[[lean_lib]]
name = "GemelTest"

[[require]]
name = "Qq"
scope = "leanprover-community"